export const DATAEN = [
  {
    id: "1",
    quest: "🇧🇪",
    ask: ["Bolivia", "Bulgaria", "Belgium", "Germany"],
    truask: "Belgium",
  },
  {
    id: "2",
    quest: "🇨🇭",
    ask: ["Denmark", "Switzerland", "Monaco", "Turkey"],
    truask: "Switzerland",
  },
  {
    id: "3",
    quest: "🇯🇵",
    ask: ["Japan", "South Korea", "Bangladesh", "Brazil"],
    truask: "Japan",
  },
  {
    id: "4",
    quest: "🇨🇿",
    ask: ["Philippines", "Czechia", "Paraguay", "Slovenia"],
    truask: "Czechia",
  },
  {
    id: "5",
    quest: "🇷🇺",
    ask: ["Ukraine", "Netherlands", "Serbia", "Russia"],
    truask: "Russia",
  },
  {
    id: "6",
    quest: "🇲🇩",
    ask: ["Guinea", "Bolivia", "Moldova", "Ecuador"],
    truask: "Moldova",
  },
  {
    id: "7",
    quest: "🇦🇷",
    ask: ["Cuba", "Argentina", "Dominica", "Honduras"],
    truask: "Argentina",
  },
  {
    id: "8",
    quest: "🇮🇱",
    ask: ["Uruguay", "Nicaragua", "Kazakhstan", "Israel"],
    truask: "Israel",
  },
  {
    id: "9",
    quest: "🇺🇸",
    ask: ["United States", "Malaysia", "Madagascar", "Liberia"],
    truask: "United States",
  },
  {
    id: "10",
    quest: "🇬🇱",
    ask: ["Gibraltar", "Guernsey", "Greenland", "Georgia"],
    truask: "Greenland",
  },
  {
    id: "11",
    quest: "🇦🇱",
    ask: ["Albania", "Bahrain", "Bermuda", "Belarus"],
    truask: "Albania",
  },
  {
    id: "12",
    quest: "🇧🇧",
    ask: ["Micronesia", "Ecuador", "Bhutan", "Barbados"],
    truask: "Barbados",
  },
  {
    id: "13",
    quest: "🇭🇳",
    ask: ["Kiribati", "Honduras", "Laos", "Luxembourg"],
    truask: "Honduras",
  },
  {
    id: "14",
    quest: "🇳🇬",
    ask: ["Nigeria", "Panama", "Palau", "Senegal"],
    truask: "Nigeria",
  },
  {
    id: "15",
    quest: "🇾🇪",
    ask: ["Libya", "Mozambique", "Palau", "Yemen"],
    truask: "Yemen",
  },
  {
    id: "16",
    quest: "🇦🇿",
    ask: ["Azerbaijan", "Armenia", "Albania", "Andorra"],
    truask: "Azerbaijan",
  },
  {
    id: "17",
    quest: "🇧🇼",
    ask: ["Bhutan", "Botswana", "Brazil", "Bahrain"],
    truask: "Botswana",
  },
  {
    id: "18",
    quest: "🇨🇮",
    ask: ["Ghana", "Guyana", "Ireland", "Côte d’Ivoire"],
    truask: "Côte d’Ivoire",
  },
  {
    id: "19",
    quest: "🇰🇪",
    ask: ["Malawi", "Latvia", "Kenya", "Kuwait"],
    truask: "Kenya",
  },
  {
    id: "20",
    quest: "🇵🇪",
    ask: ["Peru", "Poland", "Singapore", "Tonga"],
    truask: "Peru",
  },
  {
    id: "21",
    quest: "🇺🇦",
    ask: ["Venezuela", "Ukraine", "Chad", "Mali"],
    truask: "Ukraine",
  },
  {
    id: "22",
    quest: "🇵🇹",
    ask: ["Madagascar", "Oman", "Vietnam", "Portugal"],
    truask: "Portugal",
  },
  {
    id: "23",
    quest: "🇨🇱",
    ask: ["Czechia", "Chile", "Croatia", "Philippines"],
    truask: "Chile",
  },
  {
    id: "24",
    quest: "🇹🇳",
    ask: ["Vietnam", "Turkey", "Tunisia", "Singapore"],
    truask: "Tunisia",
  },
  {
    id: "25",
    quest: "🇦🇹",
    ask: ["Austria", "Denmark", "Indonesia", "Monaco"],
    truask: "Austria",
  },
  {
    id: "26",
    quest: "🇧🇴",
    ask: ["Belarus", "Bolivia", "Colombia", "Hungary"],
    truask: "Bolivia",
  },
  {
    id: "27",
    quest: "🇮🇷",
    ask: ["Lithuania", "Libya", "Iraq", "Iran"],
    truask: "Iran",
  },
  {
    id: "28",
    quest: "🇵🇼",
    ask: ["Palau", "Rwanda", "Uzbekistan", "Kazakhstan"],
    truask: "Palau",
  },
  {
    id: "29",
    quest: "🇱🇻",
    ask: ["Lithuania", "Latvia", "Qatar", "Austria"],
    truask: "Latvia",
  },
  {
    id: "30",
    quest: "🇸🇾",
    ask: ["Uruguay", "Uganda", "Thailand", "Syria"],
    truask: "Syria",
  }
];

export const DATARU = [
  {
    id: "1",
    quest: "🇧🇪",
    ask: ["Ангилья", "Остров Вознесения", "Болгария", "Германия"],
    truask: "Остров Вознесения",
  },
  {
    id: "2",
    quest: "🇧🇪",
    ask: ["english", "ask22", "ask32", "ask42"],
    truask: "ask12",
  },
  {
    id: "3",
    quest: "🇦🇨",
    ask: ["english", "ask23", "ask33", "ask43"],
    truask: "ask13",
  },
  {
    id: "4",
    quest: "🇦🇨",
    ask: ["english", "ask25", "ask36", "ask45"],
    truask: "ask14",
  },
  {
    id: "5",
    quest: "🇦🇨",
    ask: ["english", "ask26", "ask36", "ask467"],
    truask: "ask14",
  },
  {
    id: "6",
    quest: "🇧🇪",
    ask: ["Ангилья", "Остров Вознесения", "Болгария", "Германия"],
    truask: "Остров Вознесения",
  },
];
