export const DATAEN = [
  {
    id: "1",
    quest: "🇧🇪",
    ask: ["Bolivia", "Bulgaria", "Belgium", "Germany"],
    truask: "Belgium",
  },
  {
    id: "2",
    quest: "🇨🇭",
    ask: ["Denmark", "Switzerland", "Monaco", "Turkey"],
    truask: "Switzerland",
  },
  {
    id: "3",
    quest: "🇯🇵",
    ask: ["Japan", "South Korea", "Bangladesh", "Brazil"],
    truask: "Japan",
  },
  {
    id: "4",
    quest: "🇨🇿",
    ask: ["Philippines", "Czechia", "Paraguay", "Slovenia"],
    truask: "Czechia",
  },
  {
    id: "5",
    quest: "🇷🇺",
    ask: ["Ukraine", "Netherlands", "Serbia", "Russia"],
    truask: "Russia",
  },
  {
    id: "6",
    quest: "🇲🇩",
    ask: ["Guinea", "Bolivia", "Moldova", "Ecuador"],
    truask: "Moldova",
  },
  {
    id: "7",
    quest: "🇦🇷",
    ask: ["Cuba", "Argentina", "Dominica", "Honduras"],
    truask: "Argentina",
  },
  {
    id: "8",
    quest: "🇮🇱",
    ask: ["Uruguay", "Nicaragua", "Kazakhstan", "Israel"],
    truask: "Israel",
  },
  {
    id: "9",
    quest: "🇺🇸",
    ask: ["United States", "Malaysia", "Madagascar", "Liberia"],
    truask: "United States",
  },
  {
    id: "10",
    quest: "🇬🇱",
    ask: ["Gibraltar", "Guernsey", "Greenland", "Georgia"],
    truask: "Greenland",
  },
  {
    id: "11",
    quest: "🇦🇱",
    ask: ["Albania", "Bahrain", "Bermuda", "Belarus"],
    truask: "Albania",
  },
  {
    id: "12",
    quest: "🇧🇧",
    ask: ["Micronesia", "Ecuador", "Bhutan", "Barbados"],
    truask: "Barbados",
  },
  {
    id: "13",
    quest: "🇭🇳",
    ask: ["Kiribati", "Honduras", "Laos", "Luxembourg"],
    truask: "Honduras",
  },
  {
    id: "14",
    quest: "🇳🇬",
    ask: ["Nigeria", "Panama", "Palau", "Senegal"],
    truask: "Nigeria",
  },
  {
    id: "15",
    quest: "🇾🇪",
    ask: ["Libya", "Mozambique", "Palau", "Yemen"],
    truask: "Yemen",
  },
  {
    id: "16",
    quest: "🇦🇿",
    ask: ["Azerbaijan", "Armenia", "Albania", "Andorra"],
    truask: "Azerbaijan",
  },
  {
    id: "17",
    quest: "🇧🇼",
    ask: ["Bhutan", "Botswana", "Brazil", "Bahrain"],
    truask: "Botswana",
  },
  {
    id: "18",
    quest: "🇨🇮",
    ask: ["Ghana", "Guyana", "Ireland", "Côte d’Ivoire"],
    truask: "Côte d’Ivoire",
  },
  {
    id: "19",
    quest: "🇰🇪",
    ask: ["Malawi", "Latvia", "Kenya", "Kuwait"],
    truask: "Kenya",
  },
  {
    id: "20",
    quest: "🇵🇪",
    ask: ["Peru", "Poland", "Singapore", "Tonga"],
    truask: "Peru",
  },
  {
    id: "21",
    quest: "🇺🇦",
    ask: ["Venezuela", "Ukraine", "Chad", "Mali"],
    truask: "Ukraine",
  },
  {
    id: "22",
    quest: "🇵🇹",
    ask: ["Madagascar", "Oman", "Vietnam", "Portugal"],
    truask: "Portugal",
  },
  {
    id: "23",
    quest: "🇨🇱",
    ask: ["Czechia", "Chile", "Croatia", "Philippines"],
    truask: "Chile",
  },
  {
    id: "24",
    quest: "🇹🇳",
    ask: ["Vietnam", "Turkey", "Tunisia", "Singapore"],
    truask: "Tunisia",
  },
  {
    id: "25",
    quest: "🇦🇹",
    ask: ["Austria", "Denmark", "Indonesia", "Monaco"],
    truask: "Austria",
  },
  {
    id: "26",
    quest: "🇧🇴",
    ask: ["Belarus", "Bolivia", "Colombia", "Hungary"],
    truask: "Bolivia",
  },
  {
    id: "27",
    quest: "🇮🇷",
    ask: ["Lithuania", "Libya", "Iraq", "Iran"],
    truask: "Iran",
  },
  {
    id: "28",
    quest: "🇵🇼",
    ask: ["Palau", "Rwanda", "Uzbekistan", "Kazakhstan"],
    truask: "Palau",
  },
  {
    id: "29",
    quest: "🇱🇻",
    ask: ["Lithuania", "Latvia", "Qatar", "Austria"],
    truask: "Latvia",
  },
  {
    id: "30",
    quest: "🇸🇾",
    ask: ["Uruguay", "Uganda", "Thailand", "Syria"],
    truask: "Syria",
  }
];
export const DATARU = [
  {
    id: "1",
    quest: "🇧🇪",
    ask: ["Боливия", "Болгария", "Бельгия", "Германия"],
    truask: "Бельгия",
  },
  {
    id: "2",
    quest: "🇨🇭",
    ask: ["Дания", "Швейцария", "Монако", "Турция"],
    truask: "Швейцария",
  },
  {
    id: "3",
    quest: "🇯🇵",
    ask: ["Япония", "Южная Корея", "Бангладеш", "Бразилия"],
    truask: "Япония",
  },
  {
    id: "4",
    quest: "🇨🇿",
    ask: ["Филиппины", "Чехия", "Парагвай", "Словения"],
    truask: "Чехия",
  },
  {
    id: "5",
    quest: "🇷🇺",
    ask: ["Украина", "Нидерланды", "Сербия", "Россия"],
    truask: "Россия",
  },
  {
    id: "6",
    quest: "🇲🇩",
    ask: ["Гвинея", "Боливия", "Молдова", "Эквадор"],
    truask: "Молдова",
  },
  {
    id: "7",
    quest: "🇦🇷",
    ask: ["Куба", "Аргентина", "Доминика", "Гондурас"],
    truask: "Аргентина",
  },
  {
    id: "8",
    quest: "🇮🇱",
    ask: ["Уругвай", "Никарагуа", "Казахстан", "Израиль"],
    truask: "Израиль",
  },
  {
    id: "9",
    quest: "🇺🇸",
    ask: ["Соединенные Штаты", "Малайзия", "Мадагаскар", "Либерия"],
    truask: "Соединенные Штаты",
  },
  {
    id: "10",
    quest: "🇬🇱",
    ask: ["Гибралтар", "Гернси", "Гренландия", "Грузия"],
    truask: "Гренландия",
  },
  {
    id: "11",
    quest: "🇦🇱",
    ask: ["Албания", "Бахрейн", "Бермуды", "Беларусь"],
    truask: "Албания",
  },
  {
    id: "12",
    quest: "🇧🇧",
    ask: ["Микронезия", "Эквадор", "Бутан", "Барбадос"],
    truask: "Барбадос",
  },
  {
    id: "13",
    quest: "🇭🇳",
    ask: ["Кирибати", "Гондурас", "Лаос", "Люксембург"],
    truask: "Гондурас",
  },
  {
    id: "14",
    quest: "🇳🇬",
    ask: ["Нигерия", "Панама", "Палау", "Сенегал"],
    truask: "Нигерия",
  },
  {
    id: "15",
    quest: "🇾🇪",
    ask: ["Ливия", "Мозамбик", "Палау", "Йемен"],
    truask: "Йемен",
  },
  {
    id: "16",
    quest: "🇦🇿",
    ask: ["Азербайджан", "Армения", "Албания", "Андорра"],
    truask: "Азербайджан",
  },
  {
    id: "17",
    quest: "🇧🇼",
    ask: ["Бутан", "Ботсвана", "Бразилия", "Бахрейн"],
    truask: "Ботсвана",
  },
  {
    id: "18",
    quest: "🇨🇮",
    ask: ["Гана", "Гайана", "Ирландия", "Кот-д'Ивуар"],
    truask: "Кот-д'Ивуар",
  },
  {
    id: "19",
    quest: "🇰🇪",
    ask: ["Малави", "Латвия", "Кения", "Кувейт"],
    truask: "Кения",
  },
  {
    id: "20",
    quest: "🇵🇪",
    ask: ["Перу", "Польша", "Сингапур", "Тонга"],
    truask: "Перу",
  },
  {
    id: "21",
    quest: "🇺🇦",
    ask: ["Венесуэла", "Украина", "Чад", "Мали"],
    truask: "Украина",
  },
  {
    id: "22",
    quest: "🇵🇹",
    ask: ["Мадагаскар", "Оман", "Вьетнам", "Португалия"],
    truask: "Португалия",
  },
  {
    id: "23",
    quest: "🇨🇱",
    ask: ["Чехия", "Чили", "Хорватия", "Филиппины"],
    truask: "Чили",
  },
  {
    id: "24",
    quest: "🇹🇳",
    ask: ["Вьетнам", "Турция", "Тунис", "Сингапур"],
    truask: "Тунис",
  },
  {
    id: "25",
    quest: "🇦🇹",
    ask: ["Австрия", "Дания", "Индонезия", "Монако"],
    truask: "Австрия",
  },
  {
    id: "26",
    quest: "🇧🇴",
    ask: ["Беларусь", "Боливия", "Колумбия", "Венгрия"],
    truask: "Боливия",
  },
  {
    id: "27",
    quest: "🇮🇷",
    ask: ["Литва", "Ливия", "Ирак", "Иран"],
    truask: "Иран",
  },
  {
    id: "28",
    quest: "🇵🇼",
    ask: ["Палау", "Руанда", "Узбекистан", "Казахстан"],
    truask: "Палау",
  },
  {
    id: "29",
    quest: "🇱🇻",
    ask: ["Литва", "Латвия", "Катар", "Австрия"],
    truask: "Латвия",
  },
  {
    id: "30",
    quest: "🇸🇾",
    ask: ["Уругвай", "Уганда", "Таиланд", "Сирия"],
    truask: "Сирия",
  }
];


